const Title = {
  ACCESS_TOKEN_REFRESHED_SUCCESSFULLY: "Access token refreshed successfully",
  APP_IS_CONNECTED: "App is connected to the mongo DB database",
  CONNECTED: "connected",
  CUSTOM_ERROR: "This is a custom error",
  DB_CONNECTION_NOT_DEFINED:
    "DB_CONNECTION environment variable is not defined",
  EMAIL_REQUIRED: "Email is required",
  EMAIL_UNIQUE: "Email must be unique",
  ERROR_IN_GET_ME_CONTROLLER: "Error in getMe controller:",
  ERROR_OCCUR_FROM_DATABASE: "This error occur from the database connection",
  ERROR_OCCURRED: "Error occurred while connecting to the mongo db database.",
  ERROR: "error",
  INTERNAL_SERVER_ERROR: "Internal server error",
  JWT_SECRET_NOT_DEFINED: "JWT_SECRET environment variable is not defined",
  NAME_REQUIRED: "name is required",
  NAME_UNIQUE: "name must be unique",
  PASSWORD_REQUIRED: "Password is required",
  REFRESH_TOKEN_HASH_REQUIRED: "Refresh token hash is required",
  SERVER_RUNNING_ON_PORT: "server running on port",
  SUCCESS: "success",
  TOKEN_NOT_FOUND: "Token not found",
  USER_DATA_FETCHED_SUCCESSFULLY: "User data fetched successfully",
  USER_EXISTS: "User with this name or email already exists",
  USER_REFERENCE_IS_REQUIRED_FOR_SESSION:
    "User reference is required for session",
  USER_REGISTERED_SUCCESSFULLY: "User registered successfully",
  USER_AGENT_REQUIRED: "User agent is required",
  IP_ADDRESS_REQUIRED: "IP address is required",
  REFRESH_TOKEN_NOT_FOUND: "Refresh token not found",
  INVALID_REFRESH_TOKEN: "Invalid refresh token",
  LOGGED_OUT_SUCCESSFULLY: "Logged out successfully",
};

export { Title };
